# 配置端口号
server:
  port: 8081
  servlet:
    context-path: /

# 设置数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.127:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&SslMode=Required&serverTimezone=GMT%2B8
    username: yixiaobai
    password:  Pa$$w0rd
  # 设置dubbo配置
  application:
    name: 024-springboot-dubbo-ssm-provide
# 声明当前工程为服务提供者
  dubbo:
    server: true
    # 设置注册中心
    registry: zookeeper://192.168.15.127:2181
  # 设置Redis配置
  redis:
    host: 192.168.15.127
    port: 6379
    password: Pa$$w0rd
