spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.127:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&SslMode=Required&serverTimezone=GMT%2B8
    username: yixiaobai
    password: Pa$$w0rd
mybatis:
  mapper-locations: classpath:mapper/*.xml