# 设置端口号
server:
  port: 8081
  servlet:
    context-path: /

# 设置 Dubbo 的配置
spring:
  application:
    name: 021-springboot-dubbo-provider
  dubbo:
    # 当前工程是一个服务提供者
    server: true
    # 设置一个注册中心
    registry: zookeeper://192.168.15.127:2181